### ISSUE TITLE
mhprodev

### ISSUE THREAD

**Issue by Egida** [UnderLinux/UnderDDoS#1]
Ты же скопировал код 1в1 от mhddos, поменял копирайты и якобы ты его разрабатывал?
Что ты лично изменил в коде что имеешь право писать "Создано by UnderLinux" а так же указывать свой биткоин кошелёк?
p.s и кстати да, код настолько старый, что в нём не работает большинство функций

**Comment by UnderLinux** [comment]
Знаю

вс, 17 окт. 2021 г., 22:12 Egida ***@***.***>:
